name: dash_git
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  custom_lint: ^0.5.7
  envied: ^0.5.2
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^6.0.2
  flutter_riverpod: ^2.4.8
  flutter_screwdriver: ^3.1.0
  flutter_secure_storage: ^9.0.0
  flutter_web_auth_2: ^3.0.4
  http: ^0.13.6
  json_annotation: ^4.8.1
  riverpod_lint: ^2.3.6
dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
